-- MySQL Script generated by MySQL Workbench
-- Mon Sep 30 19:58:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blindtest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blindtest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blindtest` DEFAULT CHARACTER SET utf8 ;
USE `blindtest` ;

-- -----------------------------------------------------
-- Table `blindtest`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blindtest`.`level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest`.`level` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blindtest`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest`.`playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `levelId` INT NOT NULL,
  PRIMARY KEY (`id`, `levelId`),
  INDEX `fk_playlists_level_idx` (`levelId` ASC) VISIBLE,
  CONSTRAINT `fk_playlists_level`
    FOREIGN KEY (`levelId`)
    REFERENCES `blindtest`.`level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blindtest`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest`.`song` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `artist` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blindtest`.`playlist_has_song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest`.`playlist_has_song` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playlistId` INT NOT NULL,
  `songId` INT NOT NULL,
  PRIMARY KEY (`id`, `playlistId`, `songId`),
  INDEX `fk_playlists_has_song_song1_idx` (`songId` ASC) VISIBLE,
  INDEX `fk_playlists_has_song_playlists1_idx` (`id` ASC, `playlistId` ASC) VISIBLE,
  CONSTRAINT `fk_playlists_has_song_playlists1`
    FOREIGN KEY (`id` , `playlistId`)
    REFERENCES `blindtest`.`playlist` (`id` , `levelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlists_has_song_song1`
    FOREIGN KEY (`songId`)
    REFERENCES `blindtest`.`song` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blindtest`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest`.`game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playlistId` INT NULL,
  `startDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `endDate` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_game_playlists1_idx` (`playlistId` ASC) VISIBLE,
  CONSTRAINT `fk_game_playlists1`
    FOREIGN KEY (`playlistId`)
    REFERENCES `blindtest`.`playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blindtest`.`game_has_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest`.`game_has_player` (
  `gameId` INT NOT NULL,
  `playerId` INT NOT NULL,
  `score` INT NULL,
  PRIMARY KEY (`gameId`, `playerId`),
  INDEX `fk_game_has_player_player1_idx` (`playerId` ASC) VISIBLE,
  INDEX `fk_game_has_player_game1_idx` (`gameId` ASC) VISIBLE,
  CONSTRAINT `fk_game_has_player_game1`
    FOREIGN KEY (`gameId`)
    REFERENCES `blindtest`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_has_player_player1`
    FOREIGN KEY (`playerId`)
    REFERENCES `blindtest`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
