-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 17:18:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blindtest_devfest` DEFAULT CHARACTER SET utf8 ;
USE `blindtest_devfest` ;

-- -----------------------------------------------------
-- Table `mydb`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest_devfest`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `score` INT NULL DEFAULT 0,
  `avatar` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest_devfest`.`level` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest_devfest`.`playlists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `levelId` INT NOT NULL,
  PRIMARY KEY (`id`, `levelId`),
  INDEX `fk_playlists_level_idx` (`levelId` ASC),
  CONSTRAINT `fk_playlists_level`
    FOREIGN KEY (`levelId`)
    REFERENCES `mydb`.`level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest_devfest`.`song` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `artist` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlists_has_song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blindtest_devfest`.`playlists_has_song` (
  `id` INT NOT NULL,
  `playlistId` INT NOT NULL,
  `songId` INT NOT NULL,
  PRIMARY KEY (`id`, `playlistId`, `songId`),
  INDEX `fk_playlists_has_song_song1_idx` (`songId` ASC),
  INDEX `fk_playlists_has_song_playlists1_idx` (`id` ASC, `playlistId` ASC),
  CONSTRAINT `fk_playlists_has_song_playlists1`
    FOREIGN KEY (`id` , `playlistId`)
    REFERENCES `mydb`.`playlists` (`id` , `levelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlists_has_song_song1`
    FOREIGN KEY (`songId`)
    REFERENCES `mydb`.`song` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
